name: messenger-gtk
version: 0.8.0
title: GNUnet Messenger
summary: A GTK based GUI for the Messenger service of GNUnet.
description: |
  Messenger-GTK is a convergent GTK messaging application using the GNUnet Messenger service. The goal is to provide private and secure communication between any group of devices.
  
  The application provides the following features:
  * Creating direct chats and group chats
  * Managing your contacts and groups
  * Invite contacts to a group
  * Sending text messages
  * Sending voice recordings
  * Sharing files privately
  * Deleting messages with any custom delay
  * Renaming contacts
  * Exchanging contact details physically
  * Verifying contact identities
  * Switching between different accounts
  
  Chats will generally created as opt-in. So you can decide who may contact you directly and who does not, accepting to a direct chat. Leaving a chat is also always possible.
adopt-info: messenger-gtk
icon: resources/icon/full_color.svg
grade: stable
confinement: strict
base: core22

architectures:
  - build-on: arm64
    build-for: arm64
  - build-on: armhf
    build-for: armhf
  - build-on: amd64
    build-for: amd64

slots:
  messenger-gtk:
    interface: dbus
    bus: session
    name: org.gnunet.Messenger

apps:
  messenger-gtk:
    command: usr/bin/messenger-gtk
    extensions: [gnome]
    plugs:
      - desktop
      - desktop-legacy
      - wayland
      - x11
      - home
      - network
      - network-bind
      - camera
      - audio-playback
      - audio-record
      - gsettings
    desktop: usr/share/applications/org.gnunet.Messenger.desktop
    common-id: org.gnunet.Messenger.desktop

plugs:
  gtk-3-themes:
    interface: content
    target: $SNAP/share/themes
    default-provider: gtk-common-themes
  icon-themes:
    interface: content
    target: $SNAP/share/icons
    default-provider: gtk-common-themes
  sound-themes:
    interface: content
    target: $SNAP/share/sounds
    default-provider: gtk-common-themes

parts:
  gnunet:
    build-packages:
      - build-essential
      - libc6-dev
      - libgcrypt20-dev
      - recutils
      - libjansson-dev
      - libsodium-dev
      - libcurl4-gnutls-dev
      - libidn2-dev
      - libunistring-dev
      - libsqlite3-dev
      - libmicrohttpd-dev
    stage-packages:
      - libgcrypt20
      - recutils
      - libjansson4
      - libsodium23
      - libcurl3-gnutls
      - libidn2-0
      - libunistring2
      - libsqlite3-0
      - libmicrohttpd12
      - libgnutls-dane0
      - libunbound8
    source: http://ftpmirror.gnu.org/gnunet/gnunet-0.19.4.tar.gz
    plugin: autotools
    autotools-configure-parameters:
      - --prefix=/usr
      - --disable-documentation
  libgnunetchat:
    after: [ gnunet ]
    build-packages:
      - build-essential
      - libc6-dev
      - check
    source: http://ftpmirror.gnu.org/gnunet/libgnunetchat-0.1.3.tar.xz
    plugin: meson
    meson-parameters:
      - --prefix=/usr
  messenger-gtk:
    after: [ gnunet, libgnunetchat ]
    build-packages:
      - build-essential
      - libc6-dev
      - libglib2.0-dev
      - libgdk-pixbuf-2.0-dev
      - libhandy-1-dev
      - libnotify-dev
      - libqrencode-dev
      - libzbar-dev
      - libgstreamer1.0-dev
      - libgstreamer-plugins-base1.0-dev
      - desktop-file-utils
      - libffi7
    stage-packages:
      - libglib2.0-0
      - libhandy-1-0
      - libnotify4
      - libqrencode4
      - libzbar0
      - libgstreamer1.0-0
      - libgstreamer-plugins-base1.0-0 
      - gir1.2-gtk-3.0
      - gir1.2-handy-1
      - gir1.2-pango-1.0
      - locales
      - gstreamer1.0-plugins-base
      - gstreamer1.0-plugins-bad
      - gstreamer1.0-plugins-good
      - gstreamer1.0-gtk3
      - libglu1-mesa
      - freeglut3
      - libltdl7
    source: http://ftpmirror.gnu.org/gnunet/messenger-gtk-0.8.0.tar.xz
    plugin: meson
    meson-parameters:
      - --prefix=/usr
