name: messenger-gtk
version: 0.10.2
title: GNUnet Messenger
summary: A GTK based GUI for the Messenger service of GNUnet.
description: |
  Messenger-GTK is a convergent GTK messaging application using the GNUnet Messenger service. The goal is to provide private and secure communication between any group of devices.
  
  The application provides the following features:
  * Creating direct chats and group chats
  * Managing your contacts and groups
  * Invite contacts to a group
  * Sending text messages
  * Sending voice recordings
  * Sharing files privately
  * Deleting messages with any custom delay
  * Renaming contacts
  * Exchanging contact details physically
  * Verifying contact identities
  * Switching between different accounts
  * Chatting live via video or voice streaming
  * Sharing your screen with a selected group
  
  Chats will generally created as opt-in. So you can decide who may contact you directly and who does not, accepting to a direct chat. Leaving a chat is also always possible.
adopt-info: messenger-gtk
icon: resources/icon/full_color.svg
base: core24
confinement: strict
grade: stable

platforms:
  amd64:
    build-on: [amd64]
    build-for: [amd64]
  armhf:
    build-on: [armhf]
    build-for: [armhf]
  arm64:
    build-on: [arm64]
    build-for: [arm64]

slots:
  messenger-gtk:
    interface: dbus
    bus: session
    name: org.gnunet.Messenger

apps:
  messenger-gtk:
    command: usr/bin/messenger-gtk
    extensions: [gnome]
    plugs:
      - home
      - network
      - network-bind
      - camera
      - audio-playback
      - audio-record
    desktop: usr/share/applications/org.gnunet.Messenger.desktop
    common-id: org.gnunet.Messenger.desktop

parts:
  gnunet:
    build-packages:
      - libgcrypt20-dev
      - recutils
      - libjansson-dev
      - libsodium-dev
      - libcurl4-gnutls-dev
      - libidn2-dev
      - libunistring-dev
      - libsqlite3-dev
      - libmicrohttpd-dev
      - libltdl-dev
    stage-packages:
      - libgcrypt20
      - recutils
      - libjansson4
      - libsodium23
      - libcurl3t64-gnutls
      - libidn2-0
      - libunistring5
      - libsqlite3-0
      - libmicrohttpd12
      - libgnutls-dane0
      - libunbound8
      - libltdl7
    source: http://ftp.gnu.org/gnu/gnunet/gnunet-0.23.1.tar.gz
    plugin: autotools
    autotools-configure-parameters:
      - --prefix=/usr
      - --disable-documentation
  libgnunetchat:
    after: [ gnunet ]
    source: http://ftp.gnu.org/gnu/gnunet/libgnunetchat-0.5.2.tar.gz
    plugin: meson
    meson-parameters:
      - --prefix=/usr
      - --buildtype=release
  messenger-gtk:
    after: [ gnunet, libgnunetchat ]
    build-packages:
      - libqrencode-dev
      - libzbar-dev
      - libgstreamer1.0-dev
      - libgstreamer-plugins-base1.0-dev
      - libpipewire-0.3-dev
      - libportal-dev
      - libportal-gtk3-dev
      - desktop-file-utils
    stage-packages:
      - libqrencode4
      - libzbar0
      - libgstreamer1.0-0
      - libgstreamer-plugins-base1.0-0 
      - gstreamer1.0-plugins-base
      - gstreamer1.0-plugins-bad
      - gstreamer1.0-plugins-good
      - gstreamer1.0-plugins-ugly
      - gstreamer1.0-gtk3
      - gstreamer1.0-pipewire
      - gstreamer1.0-libav
      - libpipewire-0.3-0t64
      - libportal1
      - libportal-gtk3-1
    source: http://ftp.gnu.org/gnu/gnunet/messenger-gtk-0.10.2.tar.gz
    plugin: meson
    meson-parameters:
      - --prefix=/usr
      - --buildtype=release
