name: messenger-gtk
version: 0.11.0
title: GNUnet Messenger
summary: A GTK based GUI for the Messenger service of GNUnet.
description: |
  Messenger-GTK is a convergent GTK messaging application using the GNUnet Messenger service. The goal is to provide private and secure communication between any group of devices.
  
  The application provides the following features:
  * Creating direct chats and group chats
  * Managing your contacts and groups
  * Invite contacts to a group
  * Sending text messages
  * Sending voice recordings
  * Sharing files privately
  * Deleting messages with any custom delay
  * Renaming contacts
  * Exchanging contact details physically
  * Verifying contact identities
  * Switching between different accounts
  * Chatting live via video or voice streaming
  * Sharing your screen with a selected group
  * Writing notes to yourself
  
  Chats will generally created as opt-in. So you can decide who may contact you directly and who does not, accepting to a direct chat. Leaving a chat is also always possible.
website:
  - https://git.gnunet.org/messenger-gtk.git/about/
contact:
  - gnunet@thejackimonster.de
donation:
  - https://www.gnunet.org/en/ev.html
  - https://liberapay.com/GNUnet-Messenger/
source-code:
  - https://git.gnunet.org/messenger-gtk.git/
issues:
  - https://bugs.gnunet.org
license: GPL-3.0-or-later
adopt-info: messenger-gtk
icon: resources/icon/full_color.svg
base: core24
confinement: strict
grade: stable

platforms:
  amd64:
    build-on: [amd64]
    build-for: [amd64]
  arm64:
    build-on: [arm64]
    build-for: [arm64]

slots:
  messenger-gtk:
    interface: dbus
    bus: session
    name: org.gnunet.Messenger

apps:
  messenger-gtk:
    command: usr/bin/messenger-gtk
    extensions: [gnome]
    plugs:
      - home
      - network
      - network-bind
      - camera
      - audio-playback
      - audio-record
    desktop: usr/share/applications/org.gnunet.Messenger.desktop
    common-id: org.gnunet.Messenger

parts:
  gnunet:
    build-packages:
      - libgcrypt20-dev
      - recutils
      - libjansson-dev
      - libsodium-dev
      - libcurl4-gnutls-dev
      - libidn2-dev
      - libunistring-dev
      - libsqlite3-dev
      - libmicrohttpd-dev
      - libltdl-dev
    stage-packages:
      - libgcrypt20
      - recutils
      - libjansson4
      - libsodium23
      - libcurl3t64-gnutls
      - libidn2-0
      - libunistring5
      - libsqlite3-0
      - libmicrohttpd12
      - libgnutls-dane0
      - libunbound8
      - libltdl7
    source: https://ftpmirror.gnu.org/gnunet/gnunet-0.25.2.tar.gz
    source-checksum: sha512/c40d0a8108d312b0140a1acd02a0a111ba8e2d8b31f53583e1834753bf7679e1dc903fdf50b1d93f844322a78903a35a95e8997c5f9bd44a31bc0c9484b20b73
    plugin: meson
    meson-parameters:
      - --prefix=/usr
      - --buildtype=release
  libgnunetchat:
    after: [ gnunet ]
    source: https://ftpmirror.gnu.org/gnunet/libgnunetchat-0.6.0.tar.gz
    source-checksum: sha512/46402752bf6f8a5b9e66fb7863f7b4430bc2679e42df4aeade48d6f60bd6d4d77d2079ea2ef26e72faa399eda9dd2aa485c8897f2e9af55f2258794f47424851
    plugin: meson
    meson-parameters:
      - --prefix=/usr
      - --buildtype=release
  messenger-gtk:
    after: [ gnunet, libgnunetchat ]
    build-packages:
      - libqrencode-dev
      - libzbar-dev
      - libgstreamer1.0-dev
      - libgstreamer-plugins-base1.0-dev
      - libpipewire-0.3-dev
      - libportal-dev
      - libportal-gtk3-dev
      - desktop-file-utils
    stage-packages:
      - libqrencode4
      - libzbar0
      - libgstreamer1.0-0
      - libgstreamer-plugins-base1.0-0 
      - gstreamer1.0-plugins-base
      - gstreamer1.0-plugins-bad
      - gstreamer1.0-plugins-good
      - gstreamer1.0-plugins-ugly
      - gstreamer1.0-gtk3
      - gstreamer1.0-pipewire
      - gstreamer1.0-libav
      - libpipewire-0.3-0t64
      - libportal1
      - libportal-gtk3-1
    source: https://ftpmirror.gnu.org/gnunet/messenger-gtk-0.11.0.tar.gz
    source-checksum: sha512/9f0fb3d72a785d4b6a077e684ba7ae0ce4353f728414a73f08fad6a2773de0d92a7514d0d701d7b1af93e096501fa1b7852760fdede7ce688504444f7f69b582
    plugin: meson
    meson-parameters:
      - --prefix=/usr
      - --buildtype=release
